version: '3'

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./etc/ssl/certs:/certs
      - ./var/log/nginx:/var/log/nginx
    networks:
      - proxy-net

networks:
  proxy-net:
    name: ${NETWORK_NAME}
    external: true
